CREATE TABLE IF NOT EXISTS ingress_requests (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(36) NOT NULL,
    developer_name VARCHAR(255) NOT NULL,
    namespace VARCHAR(255) NOT NULL,
    deployment_name VARCHAR(255) NOT NULL,
    target_port INT UNSIGNED NOT NULL DEFAULT 80,
    service_name VARCHAR(255) NOT NULL,
    node_port INT UNSIGNED NOT NULL,
    node_ip VARCHAR(45) NOT NULL DEFAULT '192.168.33.31',
    schedule_end_minutes INT UNSIGNED NOT NULL,
    created_by_user_id INT UNSIGNED NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at DATETIME NOT NULL,
    status ENUM('active', 'expired', 'deleted', 'failed') NOT NULL DEFAULT 'active',
    deleted_at DATETIME NULL,
    deleted_by ENUM('sweeper', 'manual') NULL,
    k8s_uid VARCHAR(100) NULL,
    last_error TEXT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_ingress_requests_public_id (public_id),
    KEY idx_ingress_requests_status_expires (status, expires_at),
    KEY idx_ingress_requests_created_by (created_by_user_id),
    CONSTRAINT fk_ingress_requests_user FOREIGN KEY (created_by_user_id) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
