CREATE TABLE IF NOT EXISTS statefulset_requests (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(36) NOT NULL,
    developer_name VARCHAR(255) NOT NULL,
    namespace VARCHAR(255) NOT NULL,
    statefulset_name VARCHAR(255) NOT NULL,
    target_port INT UNSIGNED NOT NULL DEFAULT 80,
    service_name VARCHAR(255) NULL,
    node_port INT UNSIGNED NULL,
    node_ip VARCHAR(45) NOT NULL DEFAULT '192.168.33.31',
    schedule_end_minutes INT UNSIGNED NOT NULL,
    note VARCHAR(255) NULL,
    created_by_user_id INT UNSIGNED NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at DATETIME NULL,
    status ENUM('pending', 'active', 'deleting', 'expired', 'deleted', 'failed') NOT NULL DEFAULT 'pending',
    deleted_at DATETIME NULL,
    deleted_by ENUM('sweeper', 'manual') NULL,
    k8s_uid VARCHAR(100) NULL,
    last_error TEXT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_statefulset_requests_public_id (public_id),
    KEY idx_statefulset_requests_status_expires (status, expires_at),
    KEY idx_statefulset_requests_created_by (created_by_user_id),
    CONSTRAINT fk_statefulset_requests_user FOREIGN KEY (created_by_user_id) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
